# Generated by Django 6.0.3 on 2026-03-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('num_pasta', models.IntegerField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('tipo_sangue', models.CharField(blank=True, max_length=5, null=True)),
                ('quer_servir', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
