# Generated by Django 6.0.3 on 2026-03-21 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, max_length=50)),
                ('ra', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome_mae', models.CharField(blank=True, max_length=200)),
                ('nome_pai', models.CharField(blank=True, max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('data_emissao_rg', models.DateField(blank=True, null=True)),
                ('orgao_emissor_rg', models.CharField(blank=True, max_length=50)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=20)),
                ('cnh', models.CharField(blank=True, max_length=20)),
                ('estado_civil', models.CharField(blank=True, max_length=20)),
                ('nivel_ensino', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('experiencia_profissional', models.TextField(blank=True)),
                ('deseja_servir', models.BooleanField(default=False)),
                ('data_importacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('ANALISE', 'Em análise'), ('APTO', 'Apto'), ('INAPTO', 'Inapto'), ('SERVIR', 'Quer servir'), ('TITULAR', 'Titular')], default='ANALISE', max_length=15)),
                ('etapa', models.CharField(choices=[('inscrito', 'Inscrito'), ('documentos', 'Documentos Aprovados'), ('psicologia', 'Psicologia'), ('entrevista', 'Entrevista'), ('tacf', 'TACF'), ('medico', 'Exame Médico')], default='inscrito', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=20, null=True)),
                ('consideracoes', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('ivj_social', models.CharField(blank=True, max_length=100, null=True)),
                ('entrevistador', models.CharField(blank=True, max_length=200, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='ExameMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame_f1', models.DateField(blank=True, null=True)),
                ('resultado_f1', models.CharField(blank=True, max_length=50, null=True)),
                ('cid_f1', models.CharField(blank=True, max_length=20, null=True)),
                ('data_exame_f2', models.DateField(blank=True, null=True)),
                ('resultado_f2', models.CharField(blank=True, max_length=50, null=True)),
                ('cid_f2', models.CharField(blank=True, max_length=20, null=True)),
                ('parecer', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Psicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ex1', models.DateField(blank=True, null=True)),
                ('res_apto', models.BooleanField(default=False)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='TesteFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_teste', models.DateField(blank=True, null=True)),
                ('flexao', models.IntegerField(blank=True, null=True)),
                ('abdominal', models.IntegerField(blank=True, null=True)),
                ('corrida', models.FloatField(blank=True, null=True)),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
            ],
        ),
    ]
