# Generated by Django 6.0.3 on 2026-03-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='naturalidade',
            new_name='solucao',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='num_pasta',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='quer_servir',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='tipo_sangue',
        ),
    ]
