# Generated by Django 6.0.3 on 2026-03-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='importado',
            field=models.BooleanField(default=False),
        ),
    ]
