# Generated by Django 6.0.3 on 2026-03-06 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_rename_naturalidade_candidato_solucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fase1', models.DateField(blank=True, null=True)),
                ('resultado_fase1', models.CharField(blank=True, max_length=50)),
                ('data_fase2', models.DateField(blank=True, null=True)),
                ('resultado_fase2', models.CharField(blank=True, max_length=50)),
                ('cid_fase1', models.CharField(blank=True, max_length=20)),
                ('cid_fase2', models.CharField(blank=True, max_length=20)),
                ('parecer', models.TextField(blank=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
            ],
        ),
    ]
