# Generated by Django 6.0.3 on 2026-03-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_examemedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ex1', models.DateField(blank=True, null=True)),
                ('res_apto', models.BooleanField(default=False)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
            ],
        ),
    ]
