# Generated by Django 6.0.3 on 2026-03-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_psicologia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examemedico',
            old_name='data_fase1',
            new_name='data_exame_f1',
        ),
        migrations.RenameField(
            model_name='examemedico',
            old_name='data_fase2',
            new_name='data_exame_f2',
        ),
        migrations.RemoveField(
            model_name='examemedico',
            name='cid_fase1',
        ),
        migrations.RemoveField(
            model_name='examemedico',
            name='cid_fase2',
        ),
        migrations.RemoveField(
            model_name='examemedico',
            name='resultado_fase1',
        ),
        migrations.RemoveField(
            model_name='examemedico',
            name='resultado_fase2',
        ),
        migrations.AddField(
            model_name='examemedico',
            name='cid_f1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='cid_f2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='resultado_f1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examemedico',
            name='resultado_f2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examemedico',
            name='parecer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=20, null=True)),
                ('consideracoes', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('ivj_social', models.CharField(blank=True, max_length=100, null=True)),
                ('entrevistador', models.CharField(blank=True, max_length=200, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='TesteFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_teste', models.DateField(blank=True, null=True)),
                ('flexao', models.IntegerField(blank=True, null=True)),
                ('abdominal', models.IntegerField(blank=True, null=True)),
                ('corrida', models.FloatField(blank=True, null=True)),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
            ],
        ),
    ]
