# Generated by Django 6.0.3 on 2026-03-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_rename_data_fase1_examemedico_data_exame_f1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('RESIDENCIA', 'Comprovante de Residência'), ('HISTORICO', 'Histórico Escolar'), ('OUTRO', 'Outro')], max_length=20)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='candidatos.candidato')),
            ],
        ),
    ]
