# Generated by Django 6.0.3 on 2026-03-13 17:02

import candidatos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0006_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to=candidatos.models.caminho_documento),
        ),
    ]
