# Generated by Django 6.0.3 on 2026-03-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0007_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='status',
            field=models.CharField(choices=[('ANALISE', 'Em análise'), ('APTO', 'Apto'), ('INAPTO', 'Inapto'), ('SERVIR', 'Quer servir'), ('TITULAR', 'Titular')], default='ANALISE', max_length=15),
        ),
    ]
