# Generated by Django 6.0.3 on 2026-03-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0008_candidato_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='data_upload',
            new_name='data_importacao',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='solucao',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='candidato',
            name='cnh',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='data_emissao_rg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='deseja_servir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='candidato',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidato',
            name='experiencia_profissional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nivel_ensino',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidato',
            name='orgao_emissor_rg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidato',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ra',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
