# Generated by Django 6.0.3 on 2026-03-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0009_rename_data_upload_documento_data_importacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='etapa',
            field=models.CharField(choices=[('inscrito', 'Inscrito'), ('documentos', 'Documentos Aprovados'), ('psicologia', 'Psicologia'), ('entrevista', 'Entrevista'), ('tacf', 'TACF'), ('medico', 'Exame Médico')], default='inscrito', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ra',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
